config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tops#index'
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: products/id/editのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    # member do
    #   get 'buy_edit'
    #   post 'buy_update'
    # end
  end
  resources :buys, only: [:edit, :update]
  resources :products do
    resources :images, only: [:create]
  end
  resources :destinations, only: [:new, :create, :show, :edit, :update]
  resources :users, only: [:show]

  resources :signup
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/destination.rb
class Destination < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :prefecture

  # belongs_to_active_hash :prefecture
  # delegate :name, to: :prefecture
  
  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :post_code, :city, :address, presence: true
  validates :first_name, :family_name, :city, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :first_name_kana, :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :post_code, format:{with: /\A\d{3}[-]\d{4}\z/}
  # validates :phone_number, format:{with: /\A\d{11}\z/}



  

end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
self.data = [
  {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
  {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
  {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
  {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
  {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
  {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
  {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
  {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
  {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
  {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
  {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
  {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
  {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
  {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
  {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
  {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  # belongs_to :destination
  belongs_to :category
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :name, :price, :description, :status, :shipping_cost, :shipping_days, :prefecture_id, :category_id, presence: true
  validates_associated :images
  validates :images, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable,
      :validatable, password_length: 7..20
  validates :nickname, :first_name_kana,:family_name_kana,:first_name,:family_name,presence: true
  validates :email, uniqueness: true
  validates :first_name_kana, :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name, :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  
  has_many :products, dependent: :destroy
  has_one :destination, dependent: :destroy
  has_one :card, dependent: :destroy

end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_product, only: [:edit, :update]


  def edit
    @user = current_user

    
    if current_user.destination 
      @destination = @user.destination 
    end
    
  end
  
  def update
    if @product.update(destination_id: current_user.id)

      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY'] 
      card_params = { number: '4242424242424242', cvc: '123', exp_month: '1', exp_year: '2022' }
      token = Payjp::Token.create({ card: card_params }, x_payjp_direct_token_generate: true)
      customer = Payjp::Customer.create(card: token.id)
      Payjp::Charge.create(amount: @product.price, customer: customer.id, currency: 'jpy')

      redirect_to :root
      flash[:notice] = "商品を購入しました！"
    else
      render "buy_edit", flash[:alert] = { error: @product.errors.full_messages }
    end
  end

  def set_product
    @product = Product.find(params[:id])
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :description, :status, :shipping_cost, :shipping_days, :category_id, :prefecture_id, :distination_id, images_attributes:[:image]).merge(user_id: current_user.id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
    @products = Product.includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tops/index.html.haml
.top-main
  .top-visual
    .top-visual__background
      .content
        %h2.content__title
          人生を変えるフリマアプリ
        .content__text
          %p
            FURIMAはだれでもかんたんに出品・購入できる
          %p
            フリマアプリです
        .content__btn
          = link_to "#", class: "content__btn--a" do
            = image_tag 'http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', class: 'content__btn__img'
          = link_to "#", class: "content__btn--__g" do
            = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "content__btn__img"
  .introduction-first
    %h2.title
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__pic
          .number 1
          = image_tag "pict-reason-01.jpg"
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pic
          .number 2
          = image_tag "pict-reason-02.jpg"
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list.list--last
        .list__pic
          .number 3
          = image_tag "pict-reason-03.jpg"
        %h3.list__text
          手数料
          %span 業界最安
        %p.list__description
          最大3%でお得に出品&amp;購入！
  .app-dl-first
    .app-dl-first__background
      .app-dl-first-inner
        %h2.app-dl-first-inner__title 会員数日本一位
        %p.app-dl-first-inner__text
          FURIMAは、フリマアプリで最も人気。
          %br/
          出品・購入回数も業界最多です！
          %br/
          ほしかったあの商品に出会えるかもしれません。
        .app-dl-first-inner__btn
          = link_to "#", class: "app-dl-first-inner__btn--a" do
            = image_tag 'http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', class: 'app-dl-first-inner__btn__img'
          = link_to "#", class: "app-dl-first-inner__btn--g" do
            = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "app-dl-first-inner__btn__img"
  .introduction-second
    %h2.title
      FURIMAの特徴
    %ul.lists
      %li.list
        = image_tag "icon-01.png",class: "list__img"
        %h3.list__subtitle 簡単に売り買いできる
        %p.list__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.list
        = image_tag "icon-03.png",class: "list__img"
        %h3.list__subtitle 売上金は即日振込みに対応
        %p.list__text
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.list
        = image_tag "icon-04.png",class: "list__img"
        %h3.list__subtitle 様々な支払いに対応
        %p.list__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .pickup-product.pickup-product__category
    %h2.head ピックアップカテゴリー
    .productBox
      .productHead
        = link_to "#", class: "title" do
          %h3.title__text 新規投稿商品
      .productLists 
        - @products.last(5).each do |product|
          - if product.destination_id.nil?
            = link_to product_path(product.id), class: "productList" do
              .productList--img
                = image_tag product.images[0].image.url
              .productList--body
                %h3.name 
                  = product.name
                .details
                  %ul
                    %li 
                      ￥
                      = product.price
                    %li
                      %i.fa.fa-star.likeIcon
                      0
                  %p (税込)
          - else
            .productList
              .productList--img
                = image_tag product.images[0].image.url
              .productList--body
                %h3.name 
                  = product.name
                .details
                  %ul
                    %li 
                      ￥
                      = product.price
                    %li
                      %i.fa.fa-star.likeIcon
                      0
                  %p (税込)
                  売り切れました。

  .pickup-product.pickup-product__brand
    %h2.head ピックアップブランド
    .productBox
      .productHead
        = link_to "#", class: "title" do
          %h3.title__text アーカイブ
      .productLists 
        = link_to "#", class: "productList" do
          = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png",class: "productList--img"
          .productList--body
            %h3.name product3
            .details
              %ul
                %li 30000円
                %li
                  %i.fa.fa-star.likeIcon
                  0
              %p (税込)
        = link_to "#", class: "productList" do
          = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png"
          .productList--body
            %h3.name product2
            .details
              %ul
                %li 20000円
                %li
                  %i.fa.fa-star.likeIcon
                  0
              %p (税込)
        = link_to "#", class: "productList" do
          = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png"
          .productList--body
            %h3.name product1
            .details
              %ul
                %li 10000円
                %li
                  %i.fa.fa-star.likeIcon
                  0
              %p (税込)
  .app-dl-second
    .app-dl-second__background
      .inner
        %h2.inner__title
          人誰でもかんたん、人生を変えるフリマアプリ
        %p.inner__text
          今すぐ無料ダウンロード！
        .inner__btn
          = link_to "#", class: "inner__btn--a" do
            = image_tag 'http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', class: 'inner__btn__img'
          = link_to "#", class: "inner__btn--__g" do
            = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "inner__btn__img"
          
- if user_signed_in? 
  = link_to new_product_path, class: "sell-btn" do
    %span.sell-btn__text 出品する
    = image_tag "icon_camera.png",class: "sell-btn__icon"