config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tops#index'
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: products/id/editのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    # member do
    #   get 'buy_edit'
    #   post 'buy_update'
    # end
  end
  resources :buys, only: [:edit, :update]
  resources :products do
    resources :images, only: [:create]
  end
  resources :destinations, only: [:new, :create, :show, :edit, :update]
  resources :users, only: [:show]

  resources :signup
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable,
      :validatable, password_length: 7..20
  validates :nickname, :first_name_kana,:family_name_kana,:first_name,:family_name,presence: true
  validates :email, uniqueness: true
  validates :first_name_kana, :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name, :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  
  has_many :products, dependent: :destroy
  has_one :destination, dependent: :destroy
  has_one :card, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
.wraper
  .mypage
    .useredit
      %ul
        %li<
          = link_to "#" do
            基本情報変更
        %li<
          = link_to "#" do
            クレジット情報
        %li<
          = link_to "#" do
            ログアウト
    .mypage__title
      マイページ
    .userdatas
      .userdata
        .userdata__key
          ニックネーム
        .userdata__value
          フリマ次郎
      .userdata
        .userdata__key
          メールアドレス
        .userdata__value
          tarou@furima.co.jp 
      .userdata
        .userdata__key
          お名前
        .userdata__value
          山田 太郎
      .userdata
        .userdata__key
          ふりがな(ひらがな)
        .userdata__value
          やまだ たろう
      .userdata
        .userdata__key
          生年月日
        .userdata__value
          2000年4月1日
      .userdata
        .userdata__key
          自己紹介
        .userdata__value
          プログラミング始めました。よろしくお願いします!

app/views/users/show.html.haml
.wraper
  .side-bar
    %ul
      %li
        = link_to "マイページ", user_path(current_user), class: "Lists__right--btn"
      - if current_user.destination
        %li  
          = link_to "お届け先住所", destination_path
      - else
        %li  
          = link_to 'お届け先住所登録', new_destination_path

      - if current_user.card
        %li  
          = link_to "クレジット情報削除", signup_path
      - else
        %li  
          = link_to "クレジット登録", signup_index_path
      %li
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "Lists__right--btn"
  .mypage
    .mypage__title--text
      マイページ
    .userdatas
      .userdata
        .userdata__key
          ニックネーム
        .userdata__value
          = @user.nickname
      .userdata
        .userdata__key
          メールアドレス
        .userdata__value
          = @user.email
      .userdata
        .userdata__key
          お名前
        .userdata__value
          = @user.family_name
          = @user.first_name
      .userdata
        .userdata__key
          ふりがな(ひらがな)
        .userdata__value
          = @user.family_name_kana
          = @user.first_name_kana
      .userdata
        .userdata__key
          生年月日
        .userdata__value
          = @user.birth_day
          