config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tops#index'
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: products/id/editのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    # member do
    #   get 'buy_edit'
    #   post 'buy_update'
    # end
  end
  resources :buys, only: [:edit, :update]
  resources :products do
    resources :images, only: [:create]
  end
  resources :destinations, only: [:new, :create, :show, :edit, :update]
  resources :users, only: [:show]

  resources :signup
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/destination.rb
class Destination < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :prefecture

  # belongs_to_active_hash :prefecture
  # delegate :name, to: :prefecture
  
  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :post_code, :city, :address, presence: true
  validates :first_name, :family_name, :city, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :first_name_kana, :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :post_code, format:{with: /\A\d{3}[-]\d{4}\z/}
  # validates :phone_number, format:{with: /\A\d{11}\z/}



  

end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
self.data = [
  {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
  {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
  {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
  {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
  {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
  {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
  {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
  {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
  {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
  {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
  {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
  {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
  {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
  {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
  {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
  {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  # belongs_to :destination
  belongs_to :category
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :name, :price, :description, :status, :shipping_cost, :shipping_days, :prefecture_id, :category_id, presence: true
  validates_associated :images
  validates :images, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable,
      :validatable, password_length: 7..20
  validates :nickname, :first_name_kana,:family_name_kana,:first_name,:family_name,presence: true
  validates :email, uniqueness: true
  validates :first_name_kana, :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name, :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  
  has_many :products, dependent: :destroy
  has_one :destination, dependent: :destroy
  has_one :card, dependent: :destroy

end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_product, only: [:edit, :update]


  def edit
    @user = current_user

    
    if current_user.destination 
      @destination = @user.destination 
    end
    
  end
  
  def update
    if @product.update(destination_id: current_user.id)

      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY'] 
      card_params = { number: '4242424242424242', cvc: '123', exp_month: '1', exp_year: '2022' }
      token = Payjp::Token.create({ card: card_params }, x_payjp_direct_token_generate: true)
      customer = Payjp::Customer.create(card: token.id)
      Payjp::Charge.create(amount: @product.price, customer: customer.id, currency: 'jpy')

      redirect_to :root
      flash[:notice] = "商品を購入しました！"
    else
      render "buy_edit", flash[:alert] = { error: @product.errors.full_messages }
    end
  end

  def set_product
    @product = Product.find(params[:id])
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :description, :status, :shipping_cost, :shipping_days, :category_id, :prefecture_id, :distination_id, images_attributes:[:image]).merge(user_id: current_user.id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :set_card, only: [:destroy, :show]
  require 'payjp'

  def create
    @user = User.new()

    if @user.save
      session[:id] = @user.id
      sign_in User.find(session[:id]) unless user_signed_in?
    end
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY'] 

    card_params = { number: '4242424242424242', cvc: '123', exp_month: '1', exp_year: '2022' }
    token = Payjp::Token.create({ card: card_params }, x_payjp_direct_token_generate: true)

    customer = Payjp::Customer.create(card: token.id)

      @card = Card.new(                  
        user_id: current_user.id,       
        customer_id: customer.id,        
        card_id: customer.default_card   
      )

    if @card.save
      flash[:notice] = "クレジットカード情報を登録しました！"
      redirect_to root_path
    else
      redirect_to signup_index_path 
    end
  end


  def destroy 
    if @card.delete
      flash[:notice] = "クレジットカード情報を削除しました！"
      redirect_to root_path
    else
      redirect_to signup_show_path
    end
  end
  

  def show 
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    @customer = Payjp::Customer.retrieve(@card.customer_id)
  end


end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
    @products = Product.includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buys/edit.html.haml
.wrapper
  .header
  .main
    .main__contents
      %h2.main__contents__head 
        購入内容の確認

      %hr/
      .main__contents__buy-item
        .main__contents__buy-item__image
          = image_tag @product.images[0].image.url, size: "150x90"
        .main__contents__buy-item__detail
          .main__contents__buy-item__detail__name
            = @product.name
          .main__contents__buy-item__detail__value
            ¥ 
            = @product.price
            （税込）送料込み

      %hr/
      .main__contents__value
        .main__contents__value__pay 
          支払い金額
        .main__contents__value__money
          ¥ 
          = @product.price
          （税込）送料込み

      %hr/
      .main__contents__address
        - if current_user.card
          .main__contents__address__method 
            支払い方法
            %br/
          = "************4242"
          = link_to signup_path, class: "main__contents__address__link" do
            >>確認する
        - else
          .main__contents__address__method 
            支払い方法
            %br/
          .main__contents__address__method
            = link_to signup_index_path, class: "main__contents__address__link" do
              >>クレジットカードを登録する

      %hr/
      .main__contents__posts
        配送先住所
        %br/
        - if current_user.destination 
          .main__contents__posts__shipping-address 
            
            = @destination.post_code
            %br/
            = @destination.prefecture.name
            %br/
            = @destination.city
            %br/
            = @destination.address
            %br/
            = @destination.building_name
            %br/
            = @destination.family_name 
            = @destination.first_name
          .main__contents__posts__method
            = link_to edit_destination_path, class: "main__contents__address__link" do
              >>変更する
        - else
          .main__contents__posts__shipping-address 
          .main__contents__posts__method
            = link_to new_destination_path, class: "main__contents__address__link" do
              >>配送先の登録

      - if current_user.card and current_user.destination 
        %hr/
        .main__contents__send
        = form_for @product, :url => {controller: "buys", action: "update"} do |f|
          = f.submit value: "購入する", class: "btn-icon"

app/views/signup/index.html.haml
.session_wrapper
  .single_container
    .session__main
      .session__main__container
        %h2.session__main__container__title 支払い方法
        = form_with url: signup_index_path, name: "charge-form", id: 'charge-form', method: :post, html:{class: 'session__main__container__box'} do |f|
          .session__main__container__formGroup
            %label{for: "nickname"}
              カード番号
              %span.form__require 必須
              %br
            = f.text_field "number", class: "input__default", placeholder: "半角数字のみ", type: "text", id: "card_number", maxlength: "16"
            .session__main__container__formGroup__sub
              %i.fab.fa-cc-visa
              %i.fab.fa-cc-mastercard
              %i.fab.fa-cc-jcb
              %i.fab.fa-cc-discover
              %i.fab.fa-cc-amex
          .session__main__container__formGroup
            %label{for: "nickname"}
              有効期限
              %span.form__require 必須
            .session__main__container__formGroup__sub
              %select.select__wap#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "01"} 01
                %option{value: "02"} 02
                %option{value: "03"} 03
                %option{value: "04"} 04
                %option{value: "05"} 05
                %option{value: "06"} 06
                %option{value: "07"} 07
                %option{value: "08"} 08
                %option{value: "09"} 09
                %option{value: "10"} 10
                %option{value: "11"} 11
                %option{value: "12"} 12
              %p 月
              %select.select__wap#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"} 19
                %option{value: "2020"} 20
                %option{value: "2021"} 21
                %option{value: "2022"} 22
                %option{value: "2023"} 23
                %option{value: "2024"} 24
                %option{value: "2025"} 25
              %p 年
            .session__main__container__formGroup
              %label{for: "nickname"}
                セキュリティーコード
                %span.form__require 必須
              = f.text_field "cvc", class: "input__default cvc", placeholder: "カード背面3桁の番号", type: "text"
              .session__main__container__formGroup#card_token
                = f.submit "次へ進む", class: "btn_default btn_mail", id: "token_submit"

app/views/signup/show.html.haml
.cardDelete
  .cardDelete__number
    クレジットカード情報削除してよろしいですか？

  = form_tag(signup_path, method: :DELETE, id: 'charge-form', name: "inputForm") do
    %input{ type: "hidden", name: "card_id", value: "" }
    %button.btn_mail 削除する