config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tops#index'
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: products/id/editのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    # member do
    #   get 'buy_edit'
    #   post 'buy_update'
    # end
  end
  resources :buys, only: [:edit, :update]
  resources :products do
    resources :images, only: [:create]
  end
  resources :destinations, only: [:new, :create, :show, :edit, :update]
  resources :users, only: [:show]

  resources :signup
  
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  # belongs_to :destination
  belongs_to :category
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :name, :price, :description, :status, :shipping_cost, :shipping_days, :prefecture_id, :category_id, presence: true
  validates_associated :images
  validates :images, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:destroy, :show, :edit, :update]
  
  def show
  end

  def new
    @product = Product.new
    @product.images.new

    # @category_parent_array = ["---"]
    @category_parent_array = []
    #データベースから、親カテゴリーのみ抽出し、配列化
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent
      end
  end

  def create
    # binding.pry
    @product = Product.create(product_params)
    if @product.save
      redirect_to :root
      flash[:notice] = "商品を出品しました！"
    else
      flash[:alert] = "必須情報を入力してください"
      redirect_to new_product_path
  end
end

  def edit

    grandchild_category = @product.category
    child_category = grandchild_category.parent


    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent
    end
  end

  def update
    if @product.update_attributes(product_params)
      redirect_to :root
      flash[:notice] = "商品を編集しました！"
    else
      # render action: :edit
      flash[:alert] = "必須情報を入力してください"
      redirect_to edit_product_path
    end
  end


  def destroy
    @product.destroy
    flash[:notice] = "商品を削除しました！"
    redirect_to root_path

  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
  #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end


  def set_product
    @product = Product.find(params[:id])
  end
  private
  def product_params
    params.require(:product).permit(:name, :price, :description, :status, :shipping_cost, :shipping_days, :category_id, :prefecture_id, :distination_id, images_attributes:[:image, :_destroy, :id]).merge(user_id: current_user.id)
  end
  
  # 親カテゴリーのセレクトボックス
  # name = "product[parent_id]"
  # "product" => {:category_id => "選択された親カテゴリーのID", :name, :price}

  # 孫カテゴリーのセレクトボックス
  # name = "product[category_id]"
  # "category__id" => "選択された孫カテゴリーのID"



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.haml
.products
  .products__items
    = form_for @product do |f|
      #image-box
        #previews
          - if @product.persisted?
            - @product.images.each_with_index do |image, i|
              = image_tag image.image.url, data: { index: i }, width: "100", height: '100'

        = f.fields_for :images do |image|
          .js-file_group{"data-index" => "#{image.index}"}
            = image.file_field :image, class: 'js-file'
            %br/
            %span.js-remove 削除
          - if @product.persisted?
            = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
        - if @product.persisted?
          .js-file_group{"data-index" => "#{@product.images.count}"}
            = file_field_tag :image, name: "product[images_attributes][#{@product.images.count}][image]", class: 'js-file'
            .js-remove 削除








        -# .image__name 出品画像
        -# .image__required 必須
        -# .image__upload 最大４枚までアップロードできます 
        -# .image__pictures
        -#   = f.fields_for :images do |i|
        -#     .img-label
        -#       =i.label :image do
        -#         .image__picture
        -#         = i.file_field :image
        -#         .image__picture__btn 
        -#           = icon('fas', 'camera')
        -#         .image__picture__sentence
        -#           画像を登録する

                

                
            
      .items__product
        .product__name 商品名
        .product__required 必須
        = f.text_field :name, placeholder: "40文字まで", class: "product__goods"
        %br/
        %br/
        .product__name 商品の説明
        .product__required 必須
        = f.text_area :description, placeholder: "商品の説明(必須1000文字以内)", class: "product__description"
        %br/
        %br/
        .product__name カテゴリー
        .product__required 必須
        .listing-form-box
          .listing-product-detail__category
            .listing-select-wrapper
              .listing-select-wrapper__box
                = f.select :category_id, options_for_select(Category.where(ancestry: nil).map{|t|[t[:name], t[:id],{}]}, @product.category.parent.parent.id), {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
                = f.select :category_id, options_for_select(@product.category.parent.parent.children.map{|t|[t[:name], t[:id],{}]}, @product.category.parent.id), {}, {class: 'listing-select-wrapper__box--select', id: 'children_wrapper'}
                = f.select :category_id, options_for_select(@product.category.parent.children.map{|t|[t[:name], t[:id],{}]}, @product.category.id), {}, {class: 'listing-select-wrapper__box--select', id: 'grandchildren_wrapper'}
              


     
                





        %br/
        %br/

        .product__name 商品の状態
        .product__required 必須
        = f.select :status, [['新品、未使用'], ['未使用に近い'], ["目立った傷や汚れなし"], ["やや傷や汚れあり"], ["傷や汚れあり"], ["全体的に状態が悪い"]], {}, {class: "product__status"}
        

      .items__delivery
        .delivery__name 配送料の負担
        .delivery__required 必須
        = f.select :shipping_cost, [['送料込み(出品者負担)'], ['着払い(購入者負担)']], {}, {class: "delivery__cost"}
        %br/
        %br/
        .delivery__name 発送元の地域
        .delivery__required 必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name
        %br/
        %br/
        .delivery__name 発送までの日数
        .delivery__required 必須
        = f.select :shipping_days, [['1~2日で発送'], ['2~3日で発送'], ["4~7日で発送"]], {}, {class: "delivery__days"}

      .items__value
        .value__name 販売価格
        .value__required 必須
        = f.text_field :price, placeholder: "入力してください", class: "value__prize"
        = f.submit root_path, value:"編集する",  class: "value__judgment"
      

app/views/products/new.html.haml
.products
  .products__items 
    
    = form_for @product do |f|
      #image-box
        #previews
          - if @product.persisted?
            - @product.images.each_with_index do |image, i|
              = image_tag image.image.url, data: { index: i }, width: "100", height: '100'
        = f.fields_for :images do |image|
          .js-file_group{"data-index" => "#{image.index}"}
            = image.file_field :image, class: 'js-file'
            
            
      .items__product
        .product__name 商品名
        .product__required 必須
        = f.text_field :name, placeholder: "40文字まで", class: "product__goods"
        %br/
        %br/
        .product__name 商品の説明
        .product__required 必須
        = f.text_area :description, placeholder: "商品の説明(必須1000文字以内)", class: "product__description"
        %br/
        %br/
        .product__name カテゴリー
        .product__required 必須
        .listing-form-box
          .listing-product-detail__category
            .listing-select-wrapper
              .listing-select-wrapper__box
                //親カテゴリーのセレクトボックスの生成
                = f.select :category_id, options_for_select(@category_parent_array.map{|category|[category.name, category.id]}), {prompt: "選択してください"}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
                -# = f.select :category, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
               
        %br/
        %br/
        .product__name 商品の状態
        .product__required 必須
        = f.select :status, [['新品、未使用'], ['未使用に近い'], ["目立った傷や汚れなし"], ["やや傷や汚れあり"], ["傷や汚れあり"], ["全体的に状態が悪い"]], {prompt: "選択してください"}, {class: "product__status"}
        

      .items__delivery
        .delivery__name 配送料の負担
        .delivery__required 必須
        = f.select :shipping_cost, [['送料込み(出品者負担)'], ['着払い(購入者負担)']], {prompt: "選択してください"}, {class: "delivery__cost"}
        %br/
        %br/
        .delivery__name 発送元の地域
        .delivery__required 必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください"
        %br/
        %br/
        .delivery__name 発送までの日数
        .delivery__required 必須
        = f.select :shipping_days, [['1~2日で発送'], ['2~3日で発送'], ["4~7日で発送"]], {prompt: "選択してください"}, {class: "delivery__days"}

      .items__value
        .value__name 販売価格
        .value__required 必須
        ￥
        = f.text_field :price, placeholder: "入力してください", class: "value__prize"
        = f.submit root_path, value:"出品する",  class: "value__judgment"
      

app/views/products/show.html.haml
.wraper
  .main
    .topContent
      .itemBox
        %h2 
          = @product.name
        .itemBox__body
          %ul
            %li<
              = image_tag @product.images[0].image.url
              %ul
                - @product.images.each do |image|
                  %li<
                    = image_tag image.image.url,size: "75x75"

        .itemBox__price
          %span 
            ¥
            = @product.price
          .itemBox__price--detail
            (税込) 送料込み
        .itemDetail
          = @product.description
        .table
          %table
            %tbody
              %tr
                %th 出品者
                %td 
                  = @product.user.nickname
              %tr
                %th カテゴリー
                %td 
                  = link_to "#" do
                    = @product.category.parent.parent.name
                  %br
                  = link_to "#" do
                    = @product.category.parent.name
                  %br
                  = link_to "#" do
                    = @product.category.name
              %tr
                %th 商品の状態
                %td 
                  = @product.status
              %tr
                %th 配送料の負担
                %td 
                  = @product.shipping_cost
              %tr
                %th 発送元の地域
                %td 
                  = link_to "#" do
                    = @product.prefecture.name
              %tr
                %th 発送日の目安
                %td 
                  = @product.shipping_days

        .optionalArea
          %ul
            %li{:class => "likeBtn"}
              = icon('fas','star')
              お気に入り 0  
          %ul
            %li{:class => "optionalBtn"}
              = link_to "#" do
                = icon('fas','flag')
                不適切な商品の通報 





      .commentBox
        - if user_signed_in? && current_user.id == @product.user_id
          %ul.productbtn
            %li
              = link_to '編集', edit_product_path(@product), method: :get, class: "productbtn--edit"
            %li
              = link_to '削除', product_path(@product), method: :delete, class: "productbtn--destroy"
        - elsif user_signed_in?
          %button.commentBtn 
            = link_to '購入する', edit_buy_path(@product.id), class:"commentBtn"
        - else
          購入するには会員になる必要があります
          
          

    %ul.links
      %li<
        = link_to "#" do
          = icon('fas','angle-left')
          前の商品

      %li<
        = link_to "#" do
          後ろの商品
          = icon('fas','angle-right')

    .relatedItems
      = link_to "#" do
        レディースをもっと見る